#!/usr/bin/env bash
# Materialise the Test H device package.
#
# Test H is the first probe fed PRODUCTION-SHAPED input: chat-templated windows
# with real ViT features, instead of the bare token ids Tests B/C/E/F used. It
# needs NO new ctx-bins -- it reruns the same shard-0 graphs on the same two bins
# the v5 session shipped, so the package is the kit, the runner, the analyzer and
# the docs (~25 MB), and it MERGES into the 03_vl4b_v5/ folder already on device:
#
#   adb push testh/. /data/local/tmp/v5/
#
# Nothing here is over 1 GB, so it uploads in one commit and the
# upload-large-folder COMMIT stall does not apply.
#
#   qwen3vl_testh_session/
#     TEST_H_multichunk_prefill.md   <- they read this
#     README.md                             <- the 60-second version
#     testh/                                <- push this into the v5 folder
#       probe_cases.txt  run_text_probe.sh  r0_text/ r1_image/ r2_chunk0/
#     host_refs/                            <- host side; NOT pushed to device
#     analyze_realistic_probe.py            <- run after the pull
#     MANIFEST.md                           <- md5s, incl. the bins they must have
#
# Usage: assemble.sh [outdir]
set -euo pipefail
source "$(dirname "$0")/../../scripts/env.sh"

OUT=${1:-$LLMDEPLOY_DATA/bundles/qwen3vl_testh_session}
HERE=$(cd "$(dirname "$0")" && pwd)
KIT=${KIT:-$LLMDEPLOY_DATA/work/text_probe_c}
# The bins the device must ALREADY have. Not shipped -- only verified, so the
# operator can prove the 4.5 GB on their device is the bytes these references
# were computed against.
VL_BINS=${VL_BINS:-$LLMDEPLOY_DATA/work/ctxbin/qwen3vl-4b-w8a16-gqa-splitkv-u16in}

CASES="c0_chunk0 c1_chunk1 c2_chunk2"

disk_guard 2
[ -d "$KIT" ] || { echo "FATAL: no kit at $KIT -- build it on tank first:"; \
    echo "  build_text_probe_kit.py --suite r --windows <calib.npz> ..."; exit 1; }

rm -rf "$OUT"
mkdir -p "$OUT/testh"

echo "== docs =="
cp "$LLMDEPLOY_ROOT/docs/TEST_H_multichunk_prefill.md" "$OUT/"
cp "$LLMDEPLOY_ROOT/scripts/validate/analyze_realistic_probe.py" "$OUT/"
# The retraction belongs with the test: it is why this test exists at all, and
# an operator reading only the guide would not know the previous four results
# were measuring an artifact.
cp "$LLMDEPLOY_ROOT/docs/ROOTCAUSE_qwen3vl_4b_boundary_gain.md" "$OUT/"

echo "== probe kit =="
for c in $CASES; do
    [ -d "$KIT/$c" ] || { echo "FATAL: kit is missing case $c"; exit 1; }
    cp -r "$KIT/$c" "$OUT/testh/"
done
cp "$KIT/cases.json" "$OUT/testh/"
printf '%s\n' $CASES > "$OUT/testh/probe_cases.txt"
cp "$LLMDEPLOY_ROOT/configs/run_text_probe.sh" "$OUT/testh/"

# The device never reads the .npy references -- they are the HOST side of the
# comparison. Shipping them would roughly double the push for nothing.
echo "== host-side references (not pushed to the device) =="
mkdir -p "$OUT/host_refs"
for c in $CASES; do
    mkdir -p "$OUT/host_refs/$c"
    cp -r "$KIT/$c/ref" "$OUT/host_refs/$c/"
done
cp "$KIT/cases.json" "$OUT/host_refs/"
find "$OUT/testh" -name 'ref' -type d -prune -exec rm -rf {} +

# c1_chunk1 and c2_chunk2 each ship a REAL cross-chunk cache: 72 tensors of
# NKV*D*PAST fp16 = 294 MB per case. They are 94% and 88% zero respectively
# (128 and 256 populated positions of 2048), so they compress to 19 MB and
# 36 MB. c0_chunk0's cache is all zeros and ships nothing at all -- the runner's
# shared zero file serves it, saving 294 MB on a case whose cache bytes carry no
# information.
if ls "$OUT"/testh/c*/prefill_*/past_*.raw >/dev/null 2>&1; then
    echo "== compressing the cross-chunk KV caches =="
    RAW=$(du -sm "$OUT"/testh/c*/prefill_* | awk '{s+=$1} END {print s}')
    ( cd "$OUT/testh" && tar czf past_kv.tar.gz c*/prefill_*/past_*.raw \
      && rm -f c*/prefill_*/past_*.raw )
    GZ=$(du -sm "$OUT/testh/past_kv.tar.gz" | cut -f1)
    # SPLIT IT. Measured 2026-08-20: the proxy commits 231 small files in 105 s
    # but drops a single 53 MB LFS stream every time (three consecutive
    # failures at 520/290/224 s). Files the size of the rest of the kit go
    # through fine, so the tarball ships as 8 MB parts and the operator
    # reassembles. The md5 of the whole is recorded so a bad concatenation is
    # caught rather than silently feeding a truncated cache.
    KVMD5=$(md5sum "$OUT/testh/past_kv.tar.gz" | cut -d" " -f1)
    ( cd "$OUT/testh" && split -b 8M -d -a 2 past_kv.tar.gz past_kv.tar.gz.part- \
      && rm -f past_kv.tar.gz )
    NPART=$(ls "$OUT/testh"/past_kv.tar.gz.part-* | wc -l)
    echo "   ${RAW} MB of KV -> ${GZ} MB compressed -> ${NPART} parts of 8 MB"
    echo "   assembled md5: $KVMD5"
    printf '%s  past_kv.tar.gz\n' "$KVMD5" > "$OUT/testh/past_kv.tar.gz.md5"
fi

echo "== MANIFEST.md =="
{
    echo "# Test H — manifest"
    echo
    echo "Generated by \`assemble.sh\`."
    echo
    echo "## ctx-bins — NOT shipped; verify these are what you already have"
    echo
    echo "Test H reruns the graphs Tests B/C/E/F ran, on the bins the v5 session"
    echo "shipped. If these md5s do not match your device, stop and report it:"
    echo "every reference here was computed against these exact bytes."
    echo
    echo '| file | bytes | md5 |'
    echo '|---|---:|---|'
    for n in 1 2; do
        f=$VL_BINS/${n}_of_2/qwen3vl-4b-w8a16_${n}_of_2.bin
        [ -f "$f" ] || continue
        printf '| `%s` | %s | `%s` |\n' "qwen3vl-4b-w8a16_${n}_of_2.bin" \
            "$(stat -c%s "$f")" "$(md5sum "$f" | cut -d' ' -f1)"
    done
    echo
    echo "## cases — all chat-templated, real ViT features, deepstack zeroed"
    echo
    echo '| case | window | split | real rows | reference rows | host row RMS |'
    echo '|---|---|---|---:|---|---|'
    "$PY_DEPLOY" - "$KIT/cases.json" <<'PY'
import json, sys
for m in json.load(open(sys.argv[1])):
    rms = " / ".join(f"{v:.3f}" for v in m["ref_row_rms"])
    rows = ",".join(str(r) for r in m["real_rows"])
    print(f'| `{m["case"]}` | {m.get("window")} | {m.get("window_split")} | '
          f'{m.get("n_token_rows")} | {rows} | {rms} |')
PY
    echo
    echo "\`c0_chunk0\` is the ANCHOR: replayed through the same code as the"
    echo "other two, it must reproduce Test G's \`r2_chunk0\` (argmax 3175, row RMS"
    echo "2.072 / 220.330 / 1.117 / 1.428 / 0.839). If the device disagrees between"
    echo "those two on the same bins, stop -- nothing else can be read."
    echo
    echo "\`c1_chunk1\` (128 rows, 128-position cache) and \`c2_chunk2\` (21 rows,"
    echo "256-position cache, PARTIAL) ship real cross-chunk caches as"
    echo "\`testh/past_kv.tar.gz.part-*\` — **reassemble and expand before pushing**"
    echo "(guide §4); the assembled md5 is in \`past_kv.tar.gz.md5\`. The"
    echo "runner size-checks every file and stops with that hint if you do not."
    echo "\`c2_chunk2\` is the \`variant > n_process\` condition the FLOAT_16"
    echo "padding bug fired on, and is the case this test exists for."
    echo
    echo "## testh/ contents"
    echo
    echo '| file | bytes | md5 |'
    echo '|---|---:|---|'
    (cd "$OUT/testh" && find . -type f | sort | while read -r f; do
        printf '| `%s` | %s | `%s` |\n' "${f#./}" \
            "$(stat -c%s "$f")" "$(md5sum "$f" | cut -d' ' -f1)"
    done)
} > "$OUT/MANIFEST.md"

cat > "$OUT/README.md" <<'EOF'
# Test H — 60-second version

**No rebuild. No new ctx-bins.** Uses the two text bins already on your device
from the v5 session (md5s in `MANIFEST.md` — check them first).

```sh
cat testh/past_kv.tar.gz.part-* > testh/past_kv.tar.gz    # FIRST: reassemble
md5sum -c testh/past_kv.tar.gz.md5                       # then verify
tar xzf testh/past_kv.tar.gz -C testh/                   # 53 MB -> 594 MB of KV
adb push testh/. /data/local/tmp/v5/
adb shell
cd /data/local/tmp/v5 && export LD_LIBRARY_PATH=. && chmod +x qnn-net-run
sh run_text_probe.sh 2>&1 | tee text_probe_h.log
exit
adb pull /data/local/tmp/v5/text_probe_out ./text_probe_out_h
```

~2 minutes on device, ~700 MB pushed, ~150 MB pulled. Send back
`text_probe_out_h/` and `text_probe_h.log`.

## What this covers that nothing before it did

Test G exonerated shard 0 — but every probe so far, **G included**, ran a
**single chunk against an empty cache**. A real 273-token prompt is *three*
prefill calls at AR=128, and chunks 2 and 3 run against a **partially populated
cache**. That path has never executed on device.

It is also exactly where the FLOAT_16 padding bug lived: it fires only when
`variant > n_process` — the last, *partial* chunk. The dtype was fixed and
confirmed at 0.6B; the chunking path itself was never verified at 4B.

| case | rows | cache in | why |
|---|---:|---:|---|
| `c0_chunk0` | 128 | 0 | anchor — must reproduce Test G's `r2_chunk0` |
| `c1_chunk1` | 128 | 128 | first cross-chunk call |
| `c2_chunk2` | **21** | **256** | **last and partial** — the padding-bug condition |

## The prediction — please check it against what you get

| case | row 0 | row 1 | row 2 | row 3 | last |
|---|---:|---:|---:|---:|---:|
| `c0_chunk0` | 1.0001 | 1.0002 | 1.0002 | 1.0002 | 1.0000 |
| `c1_chunk1` | 1.0001 | 0.9992 | 1.0000 | 1.0000 | 0.9996 |
| `c2_chunk2` | 1.0000 | 1.0001 | 1.0001 | 1.0002 | 1.0000 |

⚠ **Lower bound, not a point estimate.** The simulation clips but does not round
to the quantization grid. On Test G it said 3.5% and the device measured 4.4%.
**Anything within ±5% is a PASS.** The finding would be a row well outside that —
especially one that appears on `c1`/`c2` but not on the `c0` anchor, or on `c2`
alone (which would be the partial-chunk padding path).

Full detail: `TEST_H_multichunk_prefill.md`.
EOF

echo
du -sh "$OUT"/* 2>/dev/null
echo
echo "Test H package complete: $OUT"
