#!/usr/bin/env bash
# Materialise the Test J device package.
#
# Test J is the first probe fed PRODUCTION-SHAPED input: chat-templated windows
# with real ViT features, instead of the bare token ids Tests B/C/E/F used. It
# needs NO new ctx-bins -- it reruns the same shard-0 graphs on the same two bins
# the v5 session shipped, so the package is the kit, the runner, the analyzer and
# the docs (~25 MB), and it MERGES into the 03_vl4b_v5/ folder already on device:
#
#   adb push testj/. /data/local/tmp/v5/
#
# Nothing here is over 1 GB, so it uploads in one commit and the
# upload-large-folder COMMIT stall does not apply.
#
#   qwen3vl_testj_session/
#     TEST_J_decode_step.md   <- they read this
#     README.md                             <- the 60-second version
#     testj/                                <- push this into the v5 folder
#       probe_cases.txt  run_text_probe.sh  r0_text/ r1_image/ r2_chunk0/
#     host_refs/                            <- host side; NOT pushed to device
#     analyze_realistic_probe.py            <- run after the pull
#     MANIFEST.md                           <- md5s, incl. the bins they must have
#
# Usage: assemble.sh [outdir]
set -euo pipefail
source "$(dirname "$0")/../../scripts/env.sh"

OUT=${1:-$LLMDEPLOY_DATA/bundles/qwen3vl_testj_session}
HERE=$(cd "$(dirname "$0")" && pwd)
KIT=${KIT:-$LLMDEPLOY_DATA/work/text_probe_j}
# The bins the device must ALREADY have. Not shipped -- only verified, so the
# operator can prove the 4.5 GB on their device is the bytes these references
# were computed against.
VL_BINS=${VL_BINS:-$LLMDEPLOY_DATA/work/ctxbin/qwen3vl-4b-w8a16-gqa-splitkv-u16in}

CASES="j0_2plus2_s1 j1_weather_s1 j2_weather_s2"

disk_guard 2
[ -d "$KIT" ] || { echo "FATAL: no kit at $KIT -- build it on tank first:"; \
    echo "  build_text_probe_kit.py --suite r --windows <calib.npz> ..."; exit 1; }

rm -rf "$OUT"
mkdir -p "$OUT/testj"

echo "== docs =="
cp "$LLMDEPLOY_ROOT/docs/TEST_J_decode_step.md" "$OUT/"
cp "$LLMDEPLOY_ROOT/scripts/validate/analyze_realistic_probe.py" "$OUT/"
# The retraction belongs with the test: it is why this test exists at all, and
# an operator reading only the guide would not know the previous four results
# were measuring an artifact.
cp "$LLMDEPLOY_ROOT/docs/ROOTCAUSE_qwen3vl_4b_boundary_gain.md" "$OUT/"

echo "== probe kit =="
for c in $CASES; do
    [ -d "$KIT/$c" ] || { echo "FATAL: kit is missing case $c"; exit 1; }
    cp -r "$KIT/$c" "$OUT/testj/"
done
cp "$KIT/cases.json" "$OUT/testj/"
printf '%s\n' $CASES > "$OUT/testj/probe_cases.txt"
cp "$LLMDEPLOY_ROOT/configs/run_text_probe.sh" "$OUT/testj/"

# The device never reads the .npy references -- they are the HOST side of the
# comparison. Shipping them would roughly double the push for nothing.
echo "== host-side references (not pushed to the device) =="
mkdir -p "$OUT/host_refs"
for c in $CASES; do
    mkdir -p "$OUT/host_refs/$c"
    cp -r "$KIT/$c/ref" "$OUT/host_refs/$c/"
done
cp "$KIT/cases.json" "$OUT/host_refs/"
find "$OUT/testj" -name 'ref' -type d -prune -exec rm -rf {} +

# c1_chunk1 and c2_chunk2 each ship a REAL cross-chunk cache: 72 tensors of
# NKV*D*PAST fp16 = 294 MB per case. They are 94% and 88% zero respectively
# (128 and 256 populated positions of 2048), so they compress to 19 MB and
# 36 MB. c0_chunk0's cache is all zeros and ships nothing at all -- the runner's
# shared zero file serves it, saving 294 MB on a case whose cache bytes carry no
# information.
if ls "$OUT"/testj/j*/decode_*/past_*.raw >/dev/null 2>&1; then
    echo "== compressing the cross-chunk KV caches =="
    RAW=$(du -sm "$OUT"/testj/j*/decode_* | awk '{s+=$1} END {print s}')
    ( cd "$OUT/testj" && tar czf past_kv.tar.gz j*/decode_*/past_*.raw \
      && rm -f j*/decode_*/past_*.raw )
    GZ=$(du -sm "$OUT/testj/past_kv.tar.gz" | cut -f1)
    # SPLIT IT SMALL. Measured 2026-08-20 against this proxy: the 231 kit files
    # (LFS-tracked too -- `.gitattributes` has *.raw -- up to ~4 MB each) commit
    # in 105 s, a single 53 MB stream fails every time, and 8 MB parts still
    # fail. The working size is the one the rest of the kit already proves, so
    # parts are 2 MB. The md5 of the whole is recorded because a silently
    # truncated cache fed to the graph would read as a device defect.
    KVMD5=$(md5sum "$OUT/testj/past_kv.tar.gz" | cut -d" " -f1)
    ( cd "$OUT/testj" && split -b 2M -d -a 3 past_kv.tar.gz past_kv.tar.gz.part- \
      && rm -f past_kv.tar.gz )
    NPART=$(ls "$OUT/testj"/past_kv.tar.gz.part-* | wc -l)
    echo "   ${RAW} MB of KV -> ${GZ} MB compressed -> ${NPART} parts of 2 MB"
    echo "   assembled md5: $KVMD5"
    printf '%s  past_kv.tar.gz\n' "$KVMD5" > "$OUT/testj/past_kv.tar.gz.md5"
fi

echo "== MANIFEST.md =="
{
    echo "# Test J — manifest"
    echo
    echo "Generated by \`assemble.sh\`."
    echo
    echo "## ctx-bins — NOT shipped; verify these are what you already have"
    echo
    echo "Test J reruns the graphs Tests B/C/E/F ran, on the bins the v5 session"
    echo "shipped. If these md5s do not match your device, stop and report it:"
    echo "every reference here was computed against these exact bytes."
    echo
    echo '| file | bytes | md5 |'
    echo '|---|---:|---|'
    for n in 1 2; do
        f=$VL_BINS/${n}_of_2/qwen3vl-4b-w8a16_${n}_of_2.bin
        [ -f "$f" ] || continue
        printf '| `%s` | %s | `%s` |\n' "qwen3vl-4b-w8a16_${n}_of_2.bin" \
            "$(stat -c%s "$f")" "$(md5sum "$f" | cut -d' ' -f1)"
    done
    echo
    echo "## cases — all chat-templated, real ViT features, deepstack zeroed"
    echo
    echo '| case | window | split | real rows | reference rows | host row RMS |'
    echo '|---|---|---|---:|---|---|'
    "$PY_DEPLOY" - "$KIT/cases.json" <<'PY'
import json, sys
for m in json.load(open(sys.argv[1])):
    rms = " / ".join(f"{v:.3f}" for v in m["ref_row_rms"])
    rows = ",".join(str(r) for r in m["real_rows"])
    print(f'| `{m["case"]}` | {m.get("window")} | {m.get("window_split")} | '
          f'{m.get("n_token_rows")} | {rows} | {rms} |')
PY
    echo
    echo "Each case hands the decode graph a HOST-BUILT version of exactly the"
    echo "state Genie should have produced at that step. **The headline number is"
    echo "the logits argmax, not the boundary gain.**"
    echo
    echo '| case | prompt | step | cache in | expected argmax |'
    echo '|---|---|---:|---|---:|'
    echo '| `j0_2plus2_s1` | templated 2+2 | 1 | 20, all prefill | **151645** `<\|im_end\|>` |'
    echo '| `j1_weather_s1` | templated weather | 1 | 18, all prefill | **9104** ` weather` |'
    echo '| `j2_weather_s2` | templated weather | 2 | 19, one written by DECODE | **4344** ` changes` |'
    echo
    echo "\`j2\` is the recurrence -- its cache contains a row the decode graph"
    echo "wrote, which is the only part of the decode path never run on device."
    echo
    echo "Genie produced 2939 \`ention\` where j0 expects 151645, and 3279"
    echo "\`aged\` where j1 expects 9104. Ground truth is the real split graphs"
    echo "with the full KV recurrence (host_generate_check.py):"
    echo "\`2+2 -> [19, 151645]\` and \`weather -> [91169, 9104, 4344, ...]\`."
    echo
    echo "## testj/ contents"
    echo
    echo '| file | bytes | md5 |'
    echo '|---|---:|---|'
    (cd "$OUT/testj" && find . -type f | sort | while read -r f; do
        printf '| `%s` | %s | `%s` |\n' "${f#./}" \
            "$(stat -c%s "$f")" "$(md5sum "$f" | cut -d' ' -f1)"
    done)
} > "$OUT/MANIFEST.md"

cat > "$OUT/README.md" <<'EOF'
# Test J — 60-second version

**No rebuild. No new ctx-bins.** ~2 minutes on device.

```sh
cat testj/past_kv.tar.gz.part-* > testj/past_kv.tar.gz   # FIRST: reassemble
md5sum -c testj/past_kv.tar.gz.md5                       # then verify
tar xzf testj/past_kv.tar.gz -C testj/                   # 10 MB -> 962 MB of KV
adb push testj/. /data/local/tmp/v5/
adb shell
cd /data/local/tmp/v5 && export LD_LIBRARY_PATH=. && chmod +x qnn-net-run
sh run_text_probe.sh 2>&1 | tee text_probe_j.log
exit
adb pull /data/local/tmp/v5/text_probe_out ./text_probe_out_j
```

## The point

Test I confirmed the prompt-form root cause **and** exposed a second defect. On
a templated prompt Genie's first token is **correct** — but that token comes
from **prefill**. The very first **decode** call is already wrong:

| prompt | correct | Genie gave |
|---|---|---|
| 2+2 | **151645** `<\|im_end\|>` | 2939 `ention` |
| weather | **9104** ` weather` | 3279 `aged` |

The correct answer to "What is 2+2?" is **two tokens** — `4` then `<|im_end|>`.
The repetition loop is a defect, not greedy-without-EOS (eos-token *is*
configured, and the graphs emit it immediately).

The graphs are not the suspect: the host does the whole recurrence correctly,
`parity_e2e_vl` is 20/20 vs HF, and Test G already ran a decode step through
**both** shards on device at 1/1 argmax. What has never been tested is who
supplies the decode step's **inputs** — Genie's cache handoff, its LUT lookup of
a generated token, its position advance.

## Expected

| case | step | expected argmax |
|---|---:|---:|
| `j0_2plus2_s1` | 1 | **151645** |
| `j1_weather_s1` | 1 | **9104** |
| `j2_weather_s2` | 2 (cache has a decode-written row) | **4344** |

**All three matching** ⇒ the decode graph is fine including the recurrence, and
the fault is entirely in Genie's feed. That is the expected outcome, and it is
what moves the bisect inside Genie.

Send back the analyzer output — the `logits chained` argmax per case is the
measurement.

Full detail: `TEST_J_decode_step.md`.
EOF

echo
du -sh "$OUT"/* 2>/dev/null
echo
echo "Test J package complete: $OUT"
