#!/usr/bin/env bash
# Materialise the Test F device package.
#
# Test F needs NO new ctx-bins. It reruns the shard-0 graphs that Tests B, C and
# E already ran, on the same two bins the v5 session shipped -- only the
# attention mask and the token placement differ, and both are ordinary graph
# inputs. So this package is the probe kit, the runner and the docs, ~25 MB,
# and it MERGES into the 03_vl4b_v5/ folder already on the device:
#
#   adb push testf/. /data/local/tmp/v5/
#
# That is also why it can be uploaded in one commit: nothing here is over 1 GB,
# so the upload-large-folder COMMIT stall does not apply.
#
#   qwen3vl_testf_session/
#     TEST_F_sink_vs_position.md   <- they read this
#     README.md                    <- the 60-second version
#     testf/                       <- push this into the v5 folder
#       probe_cases.txt            <- the four F cases (replaces the old pair)
#       run_text_probe.sh          <- unchanged runner; it is case-driven
#       f0_ctrl_dec/ fp_ctrl_pre/ f1_row0ctx/ f2_shift4/
#     analyze_test_f.py            <- host-side, run after the pull
#     MANIFEST.md                  <- md5s, incl. the bins they must already have
#
# Usage: assemble.sh [outdir]
set -euo pipefail
source "$(dirname "$0")/../../scripts/env.sh"

OUT=${1:-$LLMDEPLOY_DATA/bundles/qwen3vl_testf_session}
HERE=$(cd "$(dirname "$0")" && pwd)
KIT=${KIT:-$LLMDEPLOY_DATA/work/text_probe_f}
# The bins the device must ALREADY have. Not shipped -- only verified, so the
# operator can prove the 4.5 GB on their device is the bytes these references
# were computed against.
VL_BINS=${VL_BINS:-$LLMDEPLOY_DATA/work/ctxbin/qwen3vl-4b-w8a16-gqa-splitkv-u16in}

CASES="f0_ctrl_dec fp_ctrl_pre f1_row0ctx f2_shift4"

disk_guard 2
[ -d "$KIT" ] || { echo "FATAL: no kit at $KIT -- build it on tank first:"; \
    echo "  build_text_probe_kit.py --suite f --layer-scan ..."; exit 1; }

rm -rf "$OUT"
mkdir -p "$OUT/testf"

echo "== docs =="
cp "$LLMDEPLOY_ROOT/docs/TEST_F_sink_vs_position.md" "$OUT/"
cp "$LLMDEPLOY_ROOT/scripts/validate/analyze_test_f.py" "$OUT/"

echo "== probe kit =="
for c in $CASES; do
    [ -d "$KIT/$c" ] || { echo "FATAL: kit is missing case $c"; exit 1; }
    cp -r "$KIT/$c" "$OUT/testf/"
done
cp "$KIT/cases.json" "$OUT/testf/"
printf '%s\n' $CASES > "$OUT/testf/probe_cases.txt"
cp "$LLMDEPLOY_ROOT/configs/run_text_probe.sh" "$OUT/testf/"

# The device never reads the .npy references -- they are the HOST side of the
# comparison. Shipping them anyway would roughly double the push for nothing,
# so they stay out of testf/ and travel beside it for whoever runs the analyzer.
echo "== host-side references (not pushed to the device) =="
mkdir -p "$OUT/host_refs"
for c in $CASES; do
    mkdir -p "$OUT/host_refs/$c"
    cp -r "$KIT/$c/ref" "$OUT/host_refs/$c/"
done
cp "$KIT/cases.json" "$OUT/host_refs/"
find "$OUT/testf" -name 'ref' -type d -prune -exec rm -rf {} +

# References for the OLD case pair (decode1tok / prefill4tok), built with the
# layer scan. Those two ran in Tests B/C/E, and shard 0 wrote its 36 per-layer
# KV tensors every time. If any of those captures still exists, the layer scan
# can be run against it with NO device time -- these are the host side of that.
KIT_V5=${KIT_V5:-$LLMDEPLOY_DATA/work/text_probe_v5_ls}
if [ -d "$KIT_V5" ]; then
    echo "== host-side references for the old cases (free layer scan) =="
    mkdir -p "$OUT/host_refs_oldcases"
    for c in decode1tok prefill4tok; do
        [ -d "$KIT_V5/$c/ref" ] || continue
        mkdir -p "$OUT/host_refs_oldcases/$c"
        cp -r "$KIT_V5/$c/ref" "$OUT/host_refs_oldcases/$c/"
    done
    cp "$KIT_V5/cases.json" "$OUT/host_refs_oldcases/"
else
    echo "   (skipped: no $KIT_V5 -- old-case layer scan will not be possible)"
fi

echo "== MANIFEST.md =="
{
    echo "# Test F — manifest"
    echo
    echo "Generated by \`assemble.sh\`."
    echo
    echo "## ctx-bins — NOT shipped; verify these are what you already have"
    echo
    echo "Test F reruns the graphs Tests B/C/E ran, on the bins the v5 session"
    echo "shipped. If these md5s do not match your device, stop and report it:"
    echo "every reference here was computed against these exact bytes."
    echo
    echo '| file | bytes | md5 |'
    echo '|---|---:|---|'
    for n in 1 2; do
        f=$VL_BINS/${n}_of_2/qwen3vl-4b-w8a16_${n}_of_2.bin
        [ -f "$f" ] || continue
        printf '| `%s` | %s | `%s` |\n' "qwen3vl-4b-w8a16_${n}_of_2.bin" \
            "$(stat -c%s "$f")" "$(md5sum "$f" | cut -d' ' -f1)"
    done
    echo
    echo "## cases"
    echo
    echo '| case | graph | real rows | host row RMS |'
    echo '|---|---|---|---|'
    "$PY_DEPLOY" - "$KIT/cases.json" <<'PY'
import json, sys
for m in json.load(open(sys.argv[1])):
    rms = " / ".join(f"{v:.3f}" for v in m["ref_row_rms"])
    rows = ",".join(str(r) for r in m["real_rows"])
    print(f'| `{m["case"]}` | {m["kind"]} | {rows} | {rms} |')
PY
    echo
    echo "\`f2_shift4\` row 4 is bit-identical to \`fp_ctrl_pre\` row 0 on the host"
    echo "(max|diff| = 0.000e+00), and \`f1_row0ctx\` collapses row 0 from 107.20 to"
    echo "1.00 RMS. Both are asserted by the kit builder."
    echo
    echo "## testf/ contents"
    echo
    echo '| file | bytes | md5 |'
    echo '|---|---:|---|'
    (cd "$OUT/testf" && find . -type f | sort | while read -r f; do
        printf '| `%s` | %s | `%s` |\n' "${f#./}" \
            "$(stat -c%s "$f")" "$(md5sum "$f" | cut -d' ' -f1)"
    done)
} > "$OUT/MANIFEST.md"

cat > "$OUT/README.md" <<'EOF'
# Test F — 60-second version

**No rebuild. No new ctx-bins.** Uses the two text bins already on your device
from the v5 session (md5s in `MANIFEST.md` — check them first).

```sh
adb push testf/. /data/local/tmp/v5/
adb shell
cd /data/local/tmp/v5 && export LD_LIBRARY_PATH=. && chmod +x qnn-net-run
sh run_text_probe.sh 2>&1 | tee text_probe_f.log
exit
adb pull /data/local/tmp/v5/text_probe_out ./text_probe_out_f
```

~2 minutes on device, ~150 MB pulled. Send back `text_probe_out_f/` and
`text_probe_f.log`.

**The question it answers:** the 1.39× gain hits row 0 of prefill and the single
row of decode. Those two share only that the row attends to nothing but itself.
`f1_row0ctx` removes that condition and keeps the row index; `f2_shift4` keeps
the condition and moves the index to row 4. Whichever one carries the gain is
the cause — and the two point at different fixes.

**Also free, before you run anything:** shard 0 has been writing 36 per-layer KV
tensors on every probe run and nobody has compared them. If an older capture
still has them —

```bash
tar tzf testb_probe_out.tar.gz | grep -c 'past_value_.*\.raw'
```

— a non-zero count means we can run the layer scan with no device time at all.
Say so and send the capture.

Full detail: `TEST_F_sink_vs_position.md`.
EOF

echo
du -sh "$OUT"/* 2>/dev/null
echo
echo "Test F package complete: $OUT"
