#!/usr/bin/env bash
# Materialise the Test G device package.
#
# Test G is the first probe fed PRODUCTION-SHAPED input: chat-templated windows
# with real ViT features, instead of the bare token ids Tests B/C/E/F used. It
# needs NO new ctx-bins -- it reruns the same shard-0 graphs on the same two bins
# the v5 session shipped, so the package is the kit, the runner, the analyzer and
# the docs (~25 MB), and it MERGES into the 03_vl4b_v5/ folder already on device:
#
#   adb push testg/. /data/local/tmp/v5/
#
# Nothing here is over 1 GB, so it uploads in one commit and the
# upload-large-folder COMMIT stall does not apply.
#
#   qwen3vl_testg_session/
#     TEST_G_realistic_prompt_boundary.md   <- they read this
#     README.md                             <- the 60-second version
#     testg/                                <- push this into the v5 folder
#       probe_cases.txt  run_text_probe.sh  r0_text/ r1_image/ r2_chunk0/
#     host_refs/                            <- host side; NOT pushed to device
#     analyze_realistic_probe.py            <- run after the pull
#     MANIFEST.md                           <- md5s, incl. the bins they must have
#
# Usage: assemble.sh [outdir]
set -euo pipefail
source "$(dirname "$0")/../../scripts/env.sh"

OUT=${1:-$LLMDEPLOY_DATA/bundles/qwen3vl_testg_session}
HERE=$(cd "$(dirname "$0")" && pwd)
KIT=${KIT:-$LLMDEPLOY_DATA/work/text_probe_r}
# The bins the device must ALREADY have. Not shipped -- only verified, so the
# operator can prove the 4.5 GB on their device is the bytes these references
# were computed against.
VL_BINS=${VL_BINS:-$LLMDEPLOY_DATA/work/ctxbin/qwen3vl-4b-w8a16-gqa-splitkv-u16in}

CASES="r0_text r1_image r2_chunk0"

disk_guard 2
[ -d "$KIT" ] || { echo "FATAL: no kit at $KIT -- build it on tank first:"; \
    echo "  build_text_probe_kit.py --suite r --windows <calib.npz> ..."; exit 1; }

rm -rf "$OUT"
mkdir -p "$OUT/testg"

echo "== docs =="
cp "$LLMDEPLOY_ROOT/docs/TEST_G_realistic_prompt_boundary.md" "$OUT/"
cp "$LLMDEPLOY_ROOT/scripts/validate/analyze_realistic_probe.py" "$OUT/"
# The retraction belongs with the test: it is why this test exists at all, and
# an operator reading only the guide would not know the previous four results
# were measuring an artifact.
cp "$LLMDEPLOY_ROOT/docs/ROOTCAUSE_qwen3vl_4b_boundary_gain.md" "$OUT/"

echo "== probe kit =="
for c in $CASES; do
    [ -d "$KIT/$c" ] || { echo "FATAL: kit is missing case $c"; exit 1; }
    cp -r "$KIT/$c" "$OUT/testg/"
done
cp "$KIT/cases.json" "$OUT/testg/"
printf '%s\n' $CASES > "$OUT/testg/probe_cases.txt"
cp "$LLMDEPLOY_ROOT/configs/run_text_probe.sh" "$OUT/testg/"

# The device never reads the .npy references -- they are the HOST side of the
# comparison. Shipping them would roughly double the push for nothing.
echo "== host-side references (not pushed to the device) =="
mkdir -p "$OUT/host_refs"
for c in $CASES; do
    mkdir -p "$OUT/host_refs/$c"
    cp -r "$KIT/$c/ref" "$OUT/host_refs/$c/"
done
cp "$KIT/cases.json" "$OUT/host_refs/"
find "$OUT/testg" -name 'ref' -type d -prune -exec rm -rf {} +

echo "== MANIFEST.md =="
{
    echo "# Test G — manifest"
    echo
    echo "Generated by \`assemble.sh\`."
    echo
    echo "## ctx-bins — NOT shipped; verify these are what you already have"
    echo
    echo "Test G reruns the graphs Tests B/C/E/F ran, on the bins the v5 session"
    echo "shipped. If these md5s do not match your device, stop and report it:"
    echo "every reference here was computed against these exact bytes."
    echo
    echo '| file | bytes | md5 |'
    echo '|---|---:|---|'
    for n in 1 2; do
        f=$VL_BINS/${n}_of_2/qwen3vl-4b-w8a16_${n}_of_2.bin
        [ -f "$f" ] || continue
        printf '| `%s` | %s | `%s` |\n' "qwen3vl-4b-w8a16_${n}_of_2.bin" \
            "$(stat -c%s "$f")" "$(md5sum "$f" | cut -d' ' -f1)"
    done
    echo
    echo "## cases — all chat-templated, real ViT features, deepstack zeroed"
    echo
    echo '| case | window | split | real rows | reference rows | host row RMS |'
    echo '|---|---|---|---:|---|---|'
    "$PY_DEPLOY" - "$KIT/cases.json" <<'PY'
import json, sys
for m in json.load(open(sys.argv[1])):
    rms = " / ".join(f"{v:.3f}" for v in m["ref_row_rms"])
    rows = ",".join(str(r) for r in m["real_rows"])
    print(f'| `{m["case"]}` | {m.get("window")} | {m.get("window_split")} | '
          f'{m.get("n_token_rows")} | {rows} | {rms} |')
PY
    echo
    echo "Row 1 carries the model's real attention sink (RMS 220.3). The host"
    echo "predicts it comes through at gain 1.0002 — see the guide §3."
    echo
    echo "## testg/ contents"
    echo
    echo '| file | bytes | md5 |'
    echo '|---|---:|---|'
    (cd "$OUT/testg" && find . -type f | sort | while read -r f; do
        printf '| `%s` | %s | `%s` |\n' "${f#./}" \
            "$(stat -c%s "$f")" "$(md5sum "$f" | cut -d' ' -f1)"
    done)
} > "$OUT/MANIFEST.md"

cat > "$OUT/README.md" <<'EOF'
# Test G — 60-second version

**No rebuild. No new ctx-bins.** Uses the two text bins already on your device
from the v5 session (md5s in `MANIFEST.md` — check them first).

```sh
adb push testg/. /data/local/tmp/v5/
adb shell
cd /data/local/tmp/v5 && export LD_LIBRARY_PATH=. && chmod +x qnn-net-run
sh run_text_probe.sh 2>&1 | tee text_probe_g.log
exit
adb pull /data/local/tmp/v5/text_probe_out ./text_probe_out_g
```

~2 minutes on device, ~120 MB pulled. Send back `text_probe_out_g/` and
`text_probe_g.log`.

## Why this test replaces the last four

Tests B, C, E and F fed **bare token ids** — `decode1tok` is one word token at
position 0. Real prompts are chat-templated and start `<|im_start|>`, and that
difference was the whole result: the 1.39× boundary gain everyone has been
chasing is something the probe manufactured. On realistic input the same
measurement gives 0.9990, and the model's real attention sink (row 1, RMS 220.3,
*bigger* than the probe's) comes through clean at 1.0000.

So the production text garbage is **currently unexplained**, and this is the
first probe shaped like production. Full account:
`ROOTCAUSE_qwen3vl_4b_boundary_gain.md`.

## The prediction — please check it against what you get

The host says every row should land within ±5%, worst 1.0347:

| case | row 0 | row 1 (sink) | row 2 | row 3 | last |
|---|---:|---:|---:|---:|---:|
| `r0_text`   | 1.0001 | 1.0002 | 1.0002 | 1.0347 | 0.9999 |
| `r1_image`  | 1.0001 | 1.0002 | 1.0002 | 1.0002 | 1.0002 |
| `r2_chunk0` | 1.0001 | 1.0002 | 1.0002 | 1.0002 | 1.0000 |

**Clean** → shard 0 is fine on production input and the boundary enquiry closes;
look downstream. **Dirty** → the fault is in the ctx-bin or the converter, the
one stage the host simulation cannot model.

Full detail: `TEST_G_realistic_prompt_boundary.md`.
EOF

echo
du -sh "$OUT"/* 2>/dev/null
echo
echo "Test G package complete: $OUT"
